name: CD Pipeline

# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}

    steps:
      - name: Pull Docker Image
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: docker pull $env:DOCKER_USER/bikeshare-fastapi:latest
    
      - name: Delete Old Docker Container
        run: docker rm -f bikeshare-fastapi-container || true
      
      - name: Run Docker Container
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: docker run -it -d -p 8001:8001 --name bikeshare-fastapi-container $env.DOCKER_USER/titanic-fastapi:latest
        #run: docker run -it -d -p 8001:8001 --name bikeshare-fastapi-container durgeshshisode1988/titanic-fastapi:latest
